wandb_version: 1

Results:
  desc: null
  value:
    save_results: true
    save_dir: results/datasets_tum/2024-07-22-22-17-15
    save_trj: true
    save_trj_kf_intv: 5
    use_gui: false
    eval_rendering: true
    use_wandb: true
Dataset:
  desc: null
  value:
    type: tum
    sensor_type: depth
    pcd_downsample: 128
    pcd_downsample_init: 32
    adaptive_pointsize: true
    point_size: 0.01
    dataset_path: datasets/tum/rgbd_dataset_fr1_yolov8
    Calibration:
      fx: 517.306408
      fy: 516.469215
      cx: 318.64304
      cy: 255.313989
      k1: 0.262383
      k2: -0.953104
      p1: -0.005358
      p2: 0.002628
      k3: 1.163314
      distorted: true
      width: 640
      height: 480
      depth_scale: 5000.0
Training:
  desc: null
  value:
    init_itr_num: 1050
    init_gaussian_update: 100
    init_gaussian_reset: 500
    init_gaussian_th: 0.005
    init_gaussian_extent: 30
    tracking_itr_num: 100
    mapping_itr_num: 150
    gaussian_update_every: 150
    gaussian_update_offset: 50
    gaussian_th: 0.7
    gaussian_extent: 1.0
    gaussian_reset: 2001
    size_threshold: 20
    kf_interval: 5
    window_size: 8
    pose_window: 3
    edge_threshold: 1.1
    rgb_boundary_threshold: 0.01
    alpha: 0.9
    kf_translation: 0.08
    kf_min_translation: 0.05
    kf_overlap: 0.9
    kf_cutoff: 0.3
    prune_mode: slam
    single_thread: false
    spherical_harmonics: false
    lr:
      cam_rot_delta: 0.003
      cam_trans_delta: 0.001
opt_params:
  desc: null
  value:
    iterations: 30000
    position_lr_init: 0.00016
    position_lr_final: 1.6e-06
    position_lr_delay_mult: 0.01
    position_lr_max_steps: 30000
    feature_lr: 0.0025
    opacity_lr: 0.05
    scaling_lr: 0.001
    rotation_lr: 0.001
    percent_dense: 0.01
    lambda_dssim: 0.2
    densification_interval: 100
    opacity_reset_interval: 3000
    densify_from_iter: 500
    densify_until_iter: 15000
    densify_grad_threshold: 0.0002
model_params:
  desc: null
  value:
    sh_degree: 0
    source_path: ''
    model_path: ''
    resolution: -1
    white_background: false
    data_device: cuda
pipeline_params:
  desc: null
  value:
    convert_SHs_python: false
    compute_cov3D_python: false
inherit_from:
  desc: null
  value: configs/rgbd/tum/base_config.yaml
_wandb:
  desc: null
  value:
    python_version: 3.10.14
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721711843
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 7
      - 13
      - 16
      - 23
      4: 3.10.14
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
    m:
    - 1: frame_idx
      6:
      - 3
    - 1: ate
      5: 1
      6:
      - 1
